//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Order_items = new HashSet<Order_items>();
        }
    
        public int Id { get; set; }
        public string Bill_no { get; set; }
        public Nullable<System.DateTime> Date_time { get; set; }
        public Nullable<double> Gross_amount { get; set; }
        public Nullable<double> Service_charge_amount { get; set; }
        public Nullable<double> Vat_charge_rate { get; set; }
        public Nullable<double> Vat_charge_amount { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Net_amount { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Paid_status { get; set; }
        public Nullable<int> Table_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_items> Order_items { get; set; }
        public virtual Tables Tables { get; set; }
        public virtual User User { get; set; }
    }
}
