//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERestaurant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_items = new HashSet<Order_items>();
        }
    
        public int Id { get; set; }
        [DisplayName("Danh m?c lo?i s?n ph?m")]
        [Required(ErrorMessage ="Ph?i ch?n danh m?c s?n ph?m")]
        public Nullable<int> Category_id { get; set; }
        [Required(ErrorMessage = "Tên s?n ph?m b?t bu?c ph?i nh?p")]
        [DisplayName("Tên s?n ph?m")]
        public string Name { get; set; }
        [DisplayName("Giá cho 1 ??n v? s?n ph?m")]
        [Required(ErrorMessage ="Giá không ???c b? tr?ng")]
        [DataType(DataType.Currency,ErrorMessage ="D? li?u không ?úng ??nh d?ng")]
        public Nullable<decimal> Price { get; set; }
        [DisplayName("Mô t? s?n ph?m")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<int> Active { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_items> Order_items { get; set; }
    }
}
